parameters:
    applications:
        mapbender_user_ol2:
            title: OL2 Demo
            screenshot: screenshot.png
            description: Full desktop application showing most of the standard Mapbender elements, Openlayers 2 version
            mapEngineCode: ol2
            published: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            regionProperties:
              - name: sidepane
                properties:
                  name: accordion
                  label: mb.manager.template.region.accordion.label
            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            10: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                overview:
                    osm_overview:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            40: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        tiled: false
                        format: image/png
                        transparent: true
                        visible: true
                        opacity: 100
            elements:
                toolbar:
                    fi-button:
                        title: mb.core.featureinfo.class.title
                        tooltip: mb.core.featureinfo.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconInfoActive
                        label: false
                        target: featureinfo
                        group: featureinfo
                    print-button:
                        title: mb.core.printclient.class.title
                        tooltip: mb.core.printclient.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconPrint
                        target: printclient
                    imageexport-button:
                        title: mb.print.imageexport.class.title
                        tooltip: mb.print.imageexport.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconImageExport
                        target: imageexport
                    legend-button:
                        title: mb.core.legend.class.title
                        tooltip: mb.core.legend.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        target: legend
                        icon: iconLegend
                    wmsloader-button:
                        title: mb.wms.wmsloader.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        target: wmsloader
                        icon: iconWms
                    gps-button:
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: false
                        target: map
                    linerulerButton:
                        title: mb.core.ruler.tag.measure
                        tooltip: mb.core.ruler.tag.line
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-line-ruler
                        label: false
                        target: lineruler
                        group: rulers
                    arearulerButton:
                        title: mb.core.ruler.tag.measure
                        tooltip: mb.core.ruler.tag.area
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-area-ruler
                        label: false
                        target: arearuler
                        group: rulers
                    about:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        label: false
                        class: Mapbender\CoreBundle\Element\AboutDialog
                    poiButton:
                        title: mb.core.poi.class.title
                        tooltip: mb.core.poi.class.description
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconPoi
                        label: false
                        target: poi
                    shareUrl:
                        class: Mapbender\CoreBundle\Element\ShareUrl
                        label: false
                content:
                    map:
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [main]
                        srs: EPSG:25832
                        extents:
                            start: [361000,5619000,371150,5625000]
                            max: [-500000,4350000,1600000,6850000]
                        scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:3857","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        anchor: right-top
                        draggable: false
                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        elementType: dialog
                        autoOpen: false
                        showLayerTitle: true
                        showGroupedLayerTitle: true
                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        target: map
                        deactivateOnClose: false
                        onlyValid: true
                        displayType: tabs
                        autoActivate: false
                        printResult: true
                    wmsloader:
                        class: Mapbender\WmsBundle\Element\WmsLoader
                        target: map
                        autoOpen: false
                        defaultFormat: 'image/png'
                        defaultInfoFormat: 'text/html'
                        splitLayers: false
                    imageexport:
                        class: Mapbender\PrintBundle\Element\ImageExport
                        target: map
                    printclient:
                        class: Mapbender\CoreBundle\Element\PrintClient
                        target: map
                        templates:
                            - { template: a4portrait, label: A4 Portrait}
                            - { template: a4landscape, label: A4 Landscape}
                            - { template: a3portrait, label: A3 Portrait}
                            - { template: a3landscape, label: A3 Landscape}
                        legend_default_behaviour: false
                        optional_fields:
                            title:
                                label: Title              # label of the optional field
                                options:                  #
                                    required: true        # true or false
                    lineruler:
                        title: mb.core.ruler.tag.line
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: line
                    arearuler:
                        title: mb.core.ruler.tag.area
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: area
                    scalebar:
                        class: Mapbender\CoreBundle\Element\ScaleBar
                        target: map
                        anchor: 'left-bottom'
                        maxWidth: 200
                        units: km
                    overview:
                        class: Mapbender\CoreBundle\Element\Overview
                        target: map
                        layerset: overview
                        width: 200
                        height: 100
                        anchor: 'right-bottom'
                        maximized: true
                        fixed: false
                    scaledisplay:
                        class: Mapbender\CoreBundle\Element\ScaleDisplay
                        target: map
                        anchor: right-top
                        scalePrefix: Scale
                        unitPrefix: true
                    poi:
                        class: Mapbender\CoreBundle\Element\POI
                        target: map
                        body: 'Please take a look at this POI'
                        useMailto: false
                sidepane:
                    layertree:
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: true
                        menu: [opacity,zoomtolayer,metadata]
                    sketch:
                        class: Mapbender\CoreBundle\Element\Sketch
                        target: map
                        auto_activate: false
                    coordinatesutility:
                        class: Mapbender\CoordinatesUtilityBundle\Element\CoordinatesUtility
                        target: map
                        srsList: []
                        addMapSrsList: true
                        zoomlevel: 6
                    html-about-mapbender:
                        title: 'About Mapbender'
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content: "<p>Mapbender is an OSGeo Project. Find out more about OSGeo at<br/><a href=\"https://www.osgeo.org\" target=\"_blank\">https://www.osgeo.org</a><br/><a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\">https://www.osgeo.org/projects/mapbender/</a></p>"

                footer:
                    activityindicator:
                        class: Mapbender\CoreBundle\Element\ActivityIndicator
                    coordinates:
                        class: Mapbender\CoreBundle\Element\CoordinatesDisplay
                        target: map
                        label: false
                        empty:  "x: - y: -"
                        prefix: "x: "
                        separator:  " y: "
                    srs:
                        class: Mapbender\CoreBundle\Element\SrsSelector
                        tooltip: mb.core.srsselector.class.description
                        label: false
                        target: map
                    scaleselector:
                        class: Mapbender\CoreBundle\Element\ScaleSelector
                        tooltip: mb.core.scaleselector.class.description
                        label: false
                        target: map
                    as:
                        class: Mapbender\CoreBundle\Element\ApplicationSwitcher
                        applications: [mapbender_user_ol2, mapbender_user_basic_ol2]
                    copyrightButton:
                        title: © OpenStreetMap contributors
                        tooltip: © OpenStreetMap contributors
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        click: https://www.openstreetmap.org/copyright
                    HTML:
                        title: HTML-powered by Mapbender
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: '<span style="color: #6FB536; font-weight:bold">powered by Mapbender</span>'
                        classes: html-element-inline
