twig:
    paths:
        '%kernel.project_dir%/mapbender/src/Mapbender/CoreBundle': MapbenderCoreBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
       - '@MapbenderCore/form/fields.html.twig'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
